#!/bin/sh
#
# Simple RedQueue init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

### BEGIN INIT INFO
# Provides:             redqueue_6379
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    RedQueue simple MQ server
# Description:          RedQueue simple message queue server powered by Redis Stream.
### END INIT INFO

REDQUEUEPORT=6379
EXEC=/usr/local/bin/redqueue-server
CLIEXEC=/usr/local/bin/redqueue-cli

PIDFILE=/var/run/redqueue_${REDQUEUEPORT}.pid
CONF="/etc/redqueue/${REDQUEUEPORT}.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting RedQueue server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $REDQUEUEPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for RedQueue to shutdown ..."
                    sleep 1
                done
                echo "RedQueue stopped"
        fi
        ;;
    *)
        echo "Please use start or stop as first argument"
        ;;
esac
